# Generated by Django 3.1.7 on 2021-04-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='likes',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
