# Generated by Django 3.1.7 on 2021-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20210331_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='type',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
