# Generated by Django 3.1.7 on 2021-04-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20210404_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='likes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='userprofile',
            field=models.CharField(max_length=100),
        ),
    ]
