# Generated by Django 3.1.7 on 2021-04-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20210404_2143'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='team_table',
        ),
    ]
