# Generated by Django 3.1.7 on 2021-04-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_remove_team_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pokedex1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pokedex2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pokedex3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pokedex4',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pokedex5',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pokedex6',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
