# Generated by Django 3.1.7 on 2021-04-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_auto_20210403_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(max_length=30),
        ),
    ]
