# Generated by Django 3.1.7 on 2021-04-06 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0005_auto_20210405_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='builder.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
