# Generated by Django 3.1.7 on 2021-04-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_auto_20210406_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followlist',
            old_name='followee',
            new_name='following',
        ),
    ]
