# Generated by Django 3.1.7 on 2021-04-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_auto_20210406_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('teamname', models.CharField(max_length=30)),
            ],
        ),
    ]
